### ISSUE TITLE
Can you add support for Mega? - https://mega.nz/

### ISSUE THREAD

**Issue by abdurrehmanio** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#197]

**Comment by vineetchoudhary** [comment]
Hi @abdurrehmanio, 

mega.nz does not provide a direct download link for a file. So, when apple service requests to download a file from mega.nz it returns the HTML page. Here the Charles request for a manifest.plist file.
<img width="1397" alt="Screenshot 2020-06-07 at 1 39 39 PM" src="https://user-images.githubusercontent.com/8479436/83963593-e0651a00-a8c4-11ea-8ce7-fb51d6f8dafc.png">


I also play with other services (like getmega.net) to get a direct download link for mega.nz, but nothing works.

Also, I'm going to close this issue because there is already a similar issue opened https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/82

Thanks,
