### ISSUE TITLE
Ip block

### ISSUE THREAD

**Issue by Xakeron** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#207]
Hello. We have 60+ iPads and don't understand why service block IP address.

**Comment by vineetchoudhary** [comment]
Hi, we use GitHub pages for website hosting and your Dropbox for IPA files and other support files. So, please make sure these are not blocked on your network.

Also, we use branch.io for short links but that is optional if that got failed then we show full URL.

**Comment by Xakeron** [comment]
⁣Отправлено с помощью BlueMail ​

На 17 дек. 2020 г., 12:23, в 12:23, Vineet Choudhary <notifications@github.com> написал:п>Hi, we use GitHub pages for website hosting and your Dropbox for IPA

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
