### ISSUE TITLE
Can able to install

### ISSUE THREAD

**Issue by VijayVJ5** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#215]
## Steps to Reproduce
1.
2.

## Details

1. Which AppBox version are you using?
    - [ ] 2.7.2
    - [ ] 2.7.1
    - [ ] 2.7.0
    - [ ] 2.6.1
    - [ ] 2.6.0
    - [ ] 2.5.0
    

2. Which macOS version did you experience the issue on?
    - [ ] macOS 10.14.x
    - [ ] macOS 10.13.x
    - [ ] macOS 10.12.x
    - [ ] macOS 10.11.x
    - [ ] macOS 10.10.x
   
3. Crash Report

```
<!-- If you have the crash report, then please copy paste that here otherwise remove this option. -->
```

4. Screenshots

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  
  </code></pre>
</details>

**Comment by vineetchoudhary** [comment]
Hi, There was a payment issue with firebase which is resolved now please try again. If you are still facing the same issue please let me know here in this issue - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/209

**Comment by VijayVJ5** [comment]
Thanks for the response, but still not able to install. showing
downloading... only

**Comment by vineetchoudhary** [comment]
Hi @VijayVJ5, We are discussing the same issue here - https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/217

**Comment by vineetchoudhary** [comment]
Hi, a new version of AppBox (2.9.5) is available to download -
https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/releases/tag/2.9.5

Please let me know if you face any issues.

**Comment by VijayVJ5** [comment]
Not able to download the build please check and let me know

**Comment by VijayVJ5** [comment]
taking so long to download the build and also not showing the downloading
percentage circle... properly

**Comment by vineetchoudhary** [comment]
Hi,

Since 2 March 2021, Dropbox made some changes that break all existing apps uploaded using the AppBox version 2.9.1 or earlier. So, Please use the [latest version of AppBox](https://getappbox.com/download/) if you are facing any installation issues. Please check more details [here](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/217).

So, please download the latest version and upload your app again. Let me know if you still face any problem.
