### ISSUE TITLE
Unable to install the app in my iOS device

### ISSUE THREAD

**Issue by nikunjgabani** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#220]
I am unable to install the app on my iOS device for the last 4 days, before that I was able to install the app on my iOS device.

- App URL is opening in a web browser
- I am able to scan the QR code and open that link on the iOS device
- I am getting the install dialog
- The issue is, the downloading process is not getting started on the iOS device

![Skype_Picture_2021_03_06T08_50_10_580Z](https://user-images.githubusercontent.com/28484945/110201190-d68a3a80-7e87-11eb-93d5-d4289235eb54.jpeg)
It looks like this image

**Comment by vineetchoudhary** [comment]
Hi,

Since 2 March 2021, Dropbox made some changes that break all existing apps uploaded using the AppBox version 2.9.1 or earlier. So, Please use the [latest version of AppBox](https://getappbox.com/download/) if you are facing any installation issues. Please check more details [here](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/217).

So, please download the latest version and upload your app again. Let me know if you still face any problem.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no further response from the author. If the above solution doesn't work, please reach out so that we can investigate further.
