### ISSUE TITLE
Add "open link in safari" option in Dashboard and upload completion popup

### ISSUE THREAD

**Issue by iTamilan** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#94]
Add the "open link" in safari or default web browser( or open a web view inside App box app itself) in Dashboard & upload completion popup.

Because each time user has to copy the URL and paste into browser to cross-check their upload details.

And also add the QR code display in upload completion popup. So the user can install right away after uploading the IPA file.

And also in Downloading page, if its possible load the QR code at first page itself. Currently, if the user wants to scan QR code then user have to take one more action

**Comment by vineetchoudhary** [comment]
> And also add the QR code display in upload completion popup. So the user can install right away after uploading the IPA file.
Already there.

![screen shot 7](https://user-images.githubusercontent.com/8479436/35607460-2efee7f8-067a-11e8-8f0f-85b1687c68c5.png)
![screen shot 8](https://user-images.githubusercontent.com/8479436/35607459-2eb630ee-067a-11e8-8dc0-84ed4e386246.png)

**Comment by iTamilan** [comment]
If you load that QRCode by default below the share URL link then it would be more user-friendly

**Comment by vineetchoudhary** [comment]
Added to dashboard.
<img width="960" alt="screen shot 2018-04-14 at 5 38 58 pm" src="https://user-images.githubusercontent.com/8479436/38768032-c217dcd8-400a-11e8-8a37-ce254c8bbe84.png">

**Comment by vineetchoudhary** [comment]
> Add the "open link" in safari or default web browser in upload completion popup.

Added keyboard shortcut for this, just hit the `enter` key to open the URL on upload completion popup. Currently not going to a specific button for this, because I'm going to redesign this screen in next version. Also in the dashboard, if you hit `enter` key, selected build URL will be open in default web browser.

> And also add the QR code display in upload completion popup. So the user can install right away after uploading the IPA file.
Currently, some user facing the issue on QR code screen. When the click on show QR code button AppBox got crashed. So, if we add this to completion popup it's possible those users may not even able to copy the build URL. 

In this version, I've added a [workaround](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/commit/ddb283062c5a89d88e4c2946de638d1070e6b5b4) for this crash. If everything working well, I'll add this next version.
