### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ericlaaper** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#96]
I get an error
Errors due to bad input parameters to an API Operation. Please report the issue.

npm 5.6.0
ionic 3,19,1

diawi is working as expected

**Comment by vineetchoudhary** [comment]
Hi, can you please provide the logs. You can see the logs generated by AppBox in `File>View Log`.

![screen shot 4](https://user-images.githubusercontent.com/8479436/30270562-a14e42fc-970a-11e7-9dd7-096d54eb1698.png)

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
