### ISSUE TITLE
hiii

### ISSUE THREAD

**Issue by subbuxamarin246** [vineetchoudhary/AppBox-iOSAppsWirelessInstallation#97]
Hi Team,

When i try to upload ipa file getting following error

**Errors due to a problem on the client-side of the SDK.**

Please help on these

**Comment by vineetchoudhary** [comment]
Hi, can you please provide the logs. You can see the logs generated by AppBox in `File>View Log`.

![screen shot 4](https://user-images.githubusercontent.com/8479436/30270562-a14e42fc-970a-11e7-9dd7-096d54eb1698.png)

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
